import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/contexts/ThemeProvider";
import Nav from "@/components/nav/Nav";
import { ScrollContextProvider } from "@/contexts/ScrollContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col font-poppins">
        <ScrollContextProvider>
          <Nav />
          {children}
        </ScrollContextProvider>
      </body>
    </html>
  );
}
